### ISSUE TITLE
v0.4.5.3-chs-alpha1.0.2 -CE1.1.1 作弊选项-其它无选项+爆红

### ISSUE THREAD

**Issue by Ark-Two** [HSSkyBoy/DOL-CheatExtend#4]
![QQ图片20231229215212](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/72326210/363a407c-7bc1-4ee4-b03f-fd51d58eeeda)

MOD安装顺序：汉化包、图片包、CE1.1.1

**Comment by w154572705** [comment]
![{DA3141E3-35A9-4b9e-930C-D0FA3CC9325B}](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/155330418/f55cc5c1-5188-4ad4-ae85-02733185e440)
Mod载入即报错，且游戏内爆红。
注：仅在1.08之后的版本游戏内爆红，1.08版本报错但不爆红

**Comment by Kuru-Kiwi** [comment]
![Screenshot_20240108_155529_com vrelnir DegreesOfLewdity_edit_92672494745754](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/155954040/a3b1881a-8e3e-4cfb-b8a2-01535737d73c)
![Screenshot_20240108_155929_com vrelnir DegreesOfLewdity_edit_92689424952522](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/155954040/809aca70-77be-4940-bd0f-5ef3dd5208c3)
![Screenshot_20240108_155224_com vrelnir DegreesOfLewdity_edit_92656146869715](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/155954040/5df2cddf-a889-4c8e-90f3-ebf85f80d8da)
![Screenshot_20240108_164130_com vrelnir DegreesOfLewdity_edit_93688363033099](https://github.com/HSSkyBoy/DOL-CheatExtend/assets/155954040/0bbdb61e-811b-469a-86f4-72c789cdac25)
[debug存档.txt](https://github.com/HSSkyBoy/DOL-CheatExtend/files/13857770/debug.txt)

一共添加了3个模组，
ModI18N-0.4.5.3-chs-alpha1.1.1
GameOriginalImagePack-0.4.5.3.
CE.1.1.1

发现游戏内-作弊-其他的界面爆红，但游戏加载时无错
用的是版本0.4.5.3-(chs-alpha1.1.1)

**Comment by QUECIE** [comment]
[degrees-of-lewdity-20240317-092228.zip](https://github.com/HSSkyBoy/DOL-CheatExtend/files/14625798/degrees-of-lewdity-20240317-092228.zip)
报错文件

**Comment by HSSkyBoy** [comment]
已发布新的releases

**Comment by HSSkyBoy** [comment]
可以直接截图打开"其他"时的爆红的情况，不过应该已经修复了
